name: Bug report
description: Did you discover a bug in SABnzbd? Rapport it here!
labels:
  - Bug
body:
  - type: input
    attributes:
      label: SABnzbd version
    validations:
      required: true
  - type: input
    attributes:
      label: Operating system
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: Include error logs directly or link to extended logs on https://pastebin.com/
    validations:
      required: true